version: "3"
services:
  web-frontend:
    stdin_open: true
    build:
      context: "./client"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    environment:
      SOCKET_ENDPOINT: "http://sync-backend:4000"
    ports:
      - "3001:3000"

  sync-backend:
    build:
      context: "./sync-backend"
    environment:
      PORT: "4000"
    ports:
      - "4001:4000"
  # chat-backend:
  #   build:
  #     context: "./chat-backend"
  #   environment:
  #     PORT: "5000"
  #   ports:
  #     - "5001:5000"
