version: "3"
services:
  web-frontend:
    build:
      context: "./client"
    environment:
      SOCKET_ENDPOINT: "http://sync-backend:4000"
    ports:
      - "3000:3000"

  sync-backend:
    build:
      context: "./sync-backend"
    environment:
      PORT: "4000"
    ports:
      - "4000:4000"

  chat-backend:
    build:
      context: "./chat-backend"
    environment:
      PORT: "5000"
    ports:
      - "5000:5000"
